### PR TITLE
Updated "test" to Linux v3.18.140

### PR DESCRIPTION
**Pull request by YordiDR**
Hello,
I updated the samsung non-S kernel (as corsicanu describes it in his XDA-post) to Linux v3.18.140.
This is the latest version of the 3.18 branch at the time of this request.

I tested this on my Samsung Galaxy A5 (2017) - European model and haven't found any bugs.
I've been using this updated kernel for several days now on my daily phone and battery life seems to have improved a little bit.

### CODE REVIEW

**Comment by corsicanu** [comment]
I didn't had time to compile and test it myself (will do it soon), but i saw you have some mismerge commits so i have few questions, based on my previous experience with upstream:
1. Which toolchain you used to compile?
2. Does cpu hotplug still work?
3. Do you have any cpu core stuck on the max value without going down?
4. Does wifi have same range?
5. Does mptcp still work?

**Comment by YordiDR** [comment]
> I didn't had time to compile and test it myself (will do it soon), but i saw you have some mismerge commits so i have few questions, based on my previous experience with upstream:
> 
>     1. Which toolchain you used to compile?
> 
>     2. Does cpu hotplug still work?
> 
>     3. Do you have any cpu core stuck on the max value without going down?
> 
>     4. Does wifi have same range?
> 
>     5. Does mptcp still work?

1. I used uberTC GCC 7.2.1 as described in your HadesKernel XDA post.
2. If "CPU hotplug" means that the last 4 cores go to sleep, then yes it works.
3. No CPU cores are stuck at max value.
4. WiFi range is slightly weaker (3-4 extra meters on the 3.18.14 (34m vs 30m on 3.18.139) although that could partially be margin of error because of outside circumstances.
5. I don't know how to test MPTCP, if you can give me some pointers i can try to test it for you?

I did just notice that the primary 4 CPU cores don't go under 449 MHz whilst on your version they go to 354MHz if i'm not mistaken.
Regards, Yordi.

**Comment by corsicanu** [comment]
> > I didn't had time to compile and test it myself (will do it soon), but i saw you have some mismerge commits so i have few questions, based on my previous experience with upstream:
> > ```
> > 1. Which toolchain you used to compile?
> > 
> > 2. Does cpu hotplug still work?
> > 
> > 3. Do you have any cpu core stuck on the max value without going down?
> > 
> > 4. Does wifi have same range?
> > 
> > 5. Does mptcp still work?
> > ```
> 
> 1. I used uberTC GCC 7.2.1 as described in your HadesKernel XDA post.
> 2. If "CPU hotplug" means that the last 4 cores go to sleep, then yes it works.
> 3. No CPU cores are stuck at max value.
> 4. WiFi range is slightly weaker (3-4 extra meters on the 3.18.14 (34m vs 30m on 3.18.139) although that could partially be margin of error because of outside circumstances.
> 5. I don't know how to test MPTCP, if you can give me some pointers i can try to test it for you?
> 
> I did just notice that the primary 4 CPU cores don't go under 449 MHz whilst on your version they go to 354MHz if i'm not mistaken.
> Regards, Yordi.

I compiled and checked it, seems like somehow lmk fails in closing apps and freeing ram which eventually rebooted my phone. By any chance do you have a telegram account for easier messaging?

**Comment by YordiDR** [comment]
> > > I didn't had time to compile and test it myself (will do it soon), but i saw you have some mismerge commits so i have few questions, based on my previous experience with upstream:
> > > ```
> > > 1. Which toolchain you used to compile?
> > > 
> > > 2. Does cpu hotplug still work?
> > > 
> > > 3. Do you have any cpu core stuck on the max value without going down?
> > > 
> > > 4. Does wifi have same range?
> > > 
> > > 5. Does mptcp still work?
> > > ```
> > 
> > 
> > 
> > 1. I used uberTC GCC 7.2.1 as described in your HadesKernel XDA post.
> > 2. If "CPU hotplug" means that the last 4 cores go to sleep, then yes it works.
> > 3. No CPU cores are stuck at max value.
> > 4. WiFi range is slightly weaker (3-4 extra meters on the 3.18.14 (34m vs 30m on 3.18.139) although that could partially be margin of error because of outside circumstances.
> > 5. I don't know how to test MPTCP, if you can give me some pointers i can try to test it for you?
> > 
> > I did just notice that the primary 4 CPU cores don't go under 449 MHz whilst on your version they go to 354MHz if i'm not mistaken.
> > Regards, Yordi.
> 
> I compiled and checked it, seems like somehow lmk fails in closing apps and freeing ram which eventually rebooted my phone. By any chance do you have a telegram account for easier messaging?

Hmm, i don't seem to have this issue... I rebooted this morning but before that it was up and running for days without an issue.

Sure, my telegram username is YordiDR .

**Comment by stendro** [comment]
> I compiled and checked it, seems like somehow lmk fails in closing apps and freeing ram which eventually rebooted my phone. By any chance do you have a telegram account for easier messaging?

Hey. I found this after searching for solution to 3.18.139 android bug.
I discovered that zram would no longer load. The problem was this patch:
"binfmt_elf: switch to new creds when switching to new mm"

**Comment by YordiDR** [comment]
> > I compiled and checked it, seems like somehow lmk fails in closing apps and freeing ram which eventually rebooted my phone. By any chance do you have a telegram account for easier messaging?
> 
> Hey. I found this after searching for solution to 3.18.139 android bug.
> I discovered that zram would no longer load. The problem was this patch:
> "binfmt_elf: switch to new creds when switching to new mm"

Hello, thanks for replying.
I tried reverting said commit but the issue still persists.
Are there any other commits needed aside from "binfmt_elf: switch to new creds when switching to new mm"?
Regards, Yordi

**Comment by stendro** [comment]
> Hello, thanks for replying.
> I tried reverting said commit but the issue still persists.
> Are there any other commits needed aside from "binfmt_elf: switch to new creds when switching to new mm"?
> Regards, Yordi

No, sorry. I thought we must have experienced a similar issue, but maybe not.
I have yet to experience problems with freeing ram, it seems to be working.

Anyhow, I'm actually on Qualcomm chipset (LG G5), so the kernel is quite different.
Though the binfmt commit above did no doubt cause some issue with credentials,
probably will for other older android systems as well.

**Comment by corsicanu** [comment]
> > Hello, thanks for replying.
> > I tried reverting said commit but the issue still persists.
> > Are there any other commits needed aside from "binfmt_elf: switch to new creds when switching to new mm"?
> > Regards, Yordi
> 
> No, sorry. I thought we must have experienced a similar issue, but maybe not.
> I have yet to experience problems with freeing ram, it seems to be working.
> 
> Anyhow, I'm actually on Qualcomm chipset (LG G5), so the kernel is quite different.
> Though the binfmt commit above did no doubt cause some issue with credentials,
> probably will for other older android systems as well.

Our issue now comes only in Pie and only with upstream.
LMK fails in killing system activities, so at some point it starts killing user apps and eats all free space until it reboots due to ram panic.

image

However in .14 kernel this issue is not present:

image

**Comment by stendro** [comment]
> Our issue now comes only in Pie and only with upstream.
> LMK fails in killing system activities, so at some point it starts killing user apps and eats all free space until it reboots due to ram panic.
> 
> However in .14 kernel this issue is not present:

I see, so this appeared after going from .14 to .139 in one step? Then it might be tricky to resolve (unless perhaps you really know what you're doing, which I don't :Þ )

Upstreaming can be tricky from my experience, because of OEM and Chipset patches, backports and/or partial upstreaming already done.
There might be conflict with Exynos fixes, or Samsung features. Like for instance ZSWAP, which I noticed was somehow integrated into LMK in the last samsung update which touched that file.

LG has done a similar thing with something called HSWAP, which is like a special way of working 2 ZRAM devices.

I don't think I can actually help you though. Just putting few thoughts out there.

**Pull request merged**
